In [20]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/raw/laliga_matches_20260529_093613.csv')

In [3]:
df.head()

,match_id,country,competition,utc_date,status,season_start_year,matchday,home_team,away_team,home_goals,away_goals,winner,referee
0,438482,Spain,Primera Division,2023-08-11 17:30:00+00:00,FINISHED,2023,1,UD Almería,Rayo Vallecano de Madrid,0,2,AWAY_TEAM,Javier Alberola Rojas
1,438479,Spain,Primera Division,2023-08-11 20:00:00+00:00,FINISHED,2023,1,Sevilla FC,Valencia CF,1,2,AWAY_TEAM,José Sánchez Martínez
2,438481,Spain,Primera Division,2023-08-12 15:00:00+00:00,FINISHED,2023,1,Real Sociedad de Fútbol,Girona FC,1,1,DRAW,Francisco Hernández Maeso
3,438483,Spain,Primera Division,2023-08-12 17:30:00+00:00,FINISHED,2023,1,UD Las Palmas,RCD Mallorca,1,1,DRAW,Víctor García Verdura
4,438474,Spain,Primera Division,2023-08-12 19:30:00+00:00,FINISHED,2023,1,Athletic Club,Real Madrid CF,0,2,AWAY_TEAM,Jesús Gil Manzano

In [14]:
df_new = pd.DataFrame(df, columns=['utc_date', 'home_team', 'away_team', 'matchday', 'season_start_year','winner'])

In [85]:
df_new[(df_new['home_team'] == 'UD Almería') | (df_new['away_team'] == 'UD Almería')].head()

,utc_date,home_team,away_team,matchday,season_start_year,winner
0,2023-08-11 17:30:00+00:00,UD Almería,Rayo Vallecano de Madrid,1,2023,AWAY_TEAM
13,2023-08-19 17:30:00+00:00,UD Almería,Real Madrid CF,2,2023,AWAY_TEAM
22,2023-08-26 17:00:00+00:00,Cádiz CF,UD Almería,3,2023,DRAW
31,2023-09-01 20:00:00+00:00,UD Almería,RC Celta de Vigo,4,2023,AWAY_TEAM
45,2023-09-17 14:15:00+00:00,Villarreal CF,UD Almería,5,2023,HOME_TEAM

In [13]:
df.columns

Index(['match_id', 'country', 'competition', 'utc_date', 'status',
       'season_start_year', 'matchday', 'home_team', 'away_team', 'home_goals',
       'away_goals', 'winner', 'referee'],
      dtype='str')

## Ejemplo con un partido

In [ ]:
match = df_copy.iloc[100]

print(match)

# 5 partidos anteriores de equipo local
previous_matches_home = df_copy[((df_copy['home_team'] == match['home_team']) | (df_copy['away_team'] == match['home_team'])) & (df_copy['utc_date'] < match['utc_date'])].sort_values(by='utc_date', ascending=False).head(5)
previous_matches_home

puntos = 0
for _, row in previous_matches_home.iterrows():
    if row['home_team'] == match['home_team']:
        if row['winner'] == 'HOME_TEAM':
            puntos += 3
        elif row['winner'] == 'AWAY_TEAM':
            puntos += 0
        else:
            puntos += 1
    else:
        if row['winner'] == 'HOME_TEAM':
            puntos += 0
        elif row['winner'] == 'AWAY_TEAM':
            puntos += 3
        else:
            puntos += 1

match['home_points_last_5'] = puntos

# 5 partidos anteriores de equipo visitante
previous_matches_away = df_copy[((df_copy['home_team'] == match['away_team']) | (df_copy['away_team'] == match['away_team'])) & (df_copy['utc_date'] < match['utc_date'])].sort_values(by='utc_date', ascending=False).head(5)


puntos = 0
for _, row in previous_matches_away.iterrows():
    if row['home_team'] == match['away_team']:
        if row['winner'] == 'HOME_TEAM':
            puntos += 3
        elif row['winner'] == 'AWAY_TEAM':
            puntos += 0
        else:
            puntos += 1
    else:
        if row['winner'] == 'HOME_TEAM':
            puntos += 0
        elif row['winner'] == 'AWAY_TEAM':
            puntos += 3
        else:
            puntos += 1

match['away_points_last_5'] = puntos

utc_date             2023-10-28 12:00:00+00:00
home_team                           UD Almería
away_team                        UD Las Palmas
matchday                                    11
season_start_year                         2023
winner                               AWAY_TEAM
Name: 100, dtype: object

In [110]:
previous_matches_away

,utc_date,home_team,away_team,matchday,season_start_year,winner
94,2023-10-22 12:00:00+00:00,UD Las Palmas,Rayo Vallecano de Madrid,10,2023,AWAY_TEAM
84,2023-10-08 12:00:00+00:00,Villarreal CF,UD Las Palmas,9,2023,AWAY_TEAM
78,2023-10-02 19:00:00+00:00,UD Las Palmas,RC Celta de Vigo,8,2023,HOME_TEAM
63,2023-09-27 17:00:00+00:00,Real Madrid CF,UD Las Palmas,7,2023,HOME_TEAM
56,2023-09-24 16:30:00+00:00,UD Las Palmas,Granada CF,6,2023,HOME_TEAM

In [112]:
previous_matches_home

,utc_date,home_team,away_team,matchday,season_start_year,winner
95,2023-10-22 14:15:00+00:00,Girona FC,UD Almería,10,2023,HOME_TEAM
79,2023-10-06 19:00:00+00:00,Athletic Club,UD Almería,9,2023,HOME_TEAM
74,2023-10-01 12:00:00+00:00,UD Almería,Granada CF,8,2023,DRAW
59,2023-09-26 17:00:00+00:00,Sevilla FC,UD Almería,7,2023,HOME_TEAM
53,2023-09-23 19:00:00+00:00,UD Almería,Valencia CF,6,2023,DRAW

## Función para aplicar a todos los partidos

In [ ]:
# Create home_points_last_5 y away_points_last_5

df_copy = df_new.copy()

def get_points_last_5(team, current_date, season):
    previous_matches = df_copy[((df_copy['home_team'] == team) | (df_copy['away_team'] == team)) & (df_copy['utc_date'] < current_date) & (df_copy['season_start_year'] == season)].sort_values(by='utc_date', ascending=False).head(5)

    puntos = 0
    for _, row in previous_matches.iterrows():
        if row['home_team'] == team:
            if row['winner'] == 'HOME_TEAM':
                puntos += 3
            elif row['winner'] == 'AWAY_TEAM':
                puntos += 0
            else:
                puntos += 1
        else:
            if row['winner'] == 'HOME_TEAM':
                puntos += 0
            elif row['winner'] == 'AWAY_TEAM':
                puntos += 3
            else:
                puntos += 1
    
    return puntos

df_copy['home_points_last_5'] = df_copy.apply(lambda row: get_points_last_5(row['home_team'], row['utc_date'], row['season_start_year']), axis=1)
df_copy['away_points_last_5'] = df_copy.apply(lambda row: get_points_last_5(row['away_team'], row['utc_date'], row['season_start_year']), axis=1)

In [133]:
df_copy.loc[df_copy['season_start_year'] == 2024].head()

,utc_date,home_team,away_team,matchday,season_start_year,winner,home_points_last_5,away_points_last_5
380,2024-08-15 17:00:00+00:00,Athletic Club,Getafe CF,1,2024,DRAW,0,0
381,2024-08-15 19:30:00+00:00,Real Betis Balompié,Girona FC,1,2024,DRAW,0,0
382,2024-08-16 17:00:00+00:00,RC Celta de Vigo,Deportivo Alavés,1,2024,HOME_TEAM,0,0
383,2024-08-16 19:30:00+00:00,UD Las Palmas,Sevilla FC,1,2024,DRAW,0,0
384,2024-08-17 17:00:00+00:00,CA Osasuna,CD Leganés,1,2024,DRAW,0,0

In [135]:
type(df_copy['utc_date'].iloc[0])

str